### ISSUE TITLE
job count does not work correctly

### ISSUE THREAD

**Issue by yiling-chen** [rasca0027/ImageCroppingWebsite#7]
Starting from a fresh new user, the dashboard correctly shows the currently finished jobs is 0.
The dashboard also correctly show 1 after finishing one job.
However, after submitting the second jobs, the dashboard shows 10 finished job.
After the third job, the dashboard shows 12 finished jobs.
After the fourth job, the dashboard shows 22 finished jobs.
After the fifth job, the dashboard shows 23 finished jobs.
After the sixth job, the dashboard shows 24 finished jobs.

Still don't know the pattern, but something wrong.

**Comment by rasca0027** [comment]
我沒有這個問題。你是不是按太多下？

**Comment by yiling-chen** [comment]
Please block multiple clicks and we may get this site online. :)

**Comment by yiling-chen** [comment]
Can you also block mouse input when clicking the "No" button?
I found that the response time is also long enough to submit multiple clicks, which results in redundant jobs.
